version: '3'
services:
  cma:
    image: whoville:latest
    entrypoint: ./cma_start.sh
    network_mode: host
  town1:
    image: whoville:latest
    entrypoint: ./town_start.sh
    network_mode: host
  town2:
    image: whoville:latest
    entrypoint: ./town_start.sh
    network_mode: host
  # town3:
  #   image: whoville:latest
  #   entrypoint: ./town_start.sh
  #   network_mode: host
  # town4:
  #   image: whoville:latest
  #   entrypoint: ./town_start.sh
  #   network_mode: host
  # town5:
  #   image: whoville:latest
  #   entrypoint: ./town_start.sh
  #   network_mode: host
